//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecouverteEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Droide
    {
        public decimal Id { get; set; }
        public string Nom { get; set; }
        public string Matricule { get; set; }
        public System.DateTime DateCreation { get; set; }
        public Nullable<System.DateTime> DateDerniereMiseAJour { get; set; }
        public Nullable<decimal> EquipeCombatId { get; set; }
        public Nullable<decimal> VaisseauId { get; set; }
    
        public virtual EquipeCombat EquipeCombat { get; set; }
    }
}
